services:
  pingvin-share-x:
    container_name: pingvin-share-x
    build: .
    restart: unless-stopped
    depends_on:
      clamav:
        condition: service_healthy
    ports:
      - 3001:3000
    environment:
      - TRUST_PROXY=false
    volumes:
      - "./data:/opt/app/backend/data:rw,z"
      - "./data/images:/opt/app/frontend/public/img:rw,z"
#      - "./config.yaml:/opt/app/config.yaml"

  clamav:
    container_name: pingvin-share-x-clamav
    restart: unless-stopped
    image: clamav/clamav-debian:latest

