import { test, expect } from '@playwright/test';
import fs from 'fs';

test.use({ storageState: 'tests/e2e/.auth/user.json' });

test('test', async ({ page }, testInfo) => {
  await page.goto('http://localhost:3000/');

  // Generate a random temporary file
  const fileName = `test-${Math.random().toString(36).substring(7)}.txt`;
  const filePath = testInfo.outputPath(fileName);
  fs.writeFileSync(filePath, 'This is a test file generated by Playwright.');

  await page.locator('input[type="file"]').setInputFiles(filePath);
  await expect(page.getByRole('cell', { name: fileName })).toBeVisible();
  await page.getByRole('button', { name: 'Share' }).click();
  await expect(page.locator('div').filter({ hasText: /^Create Share$/ })).toBeVisible();  
  await page.getByRole('button', { name: 'Share' }).click();
  await expect(page.getByRole('textbox', { name: 'Link' })).toBeVisible();
  const shareLink = await page.getByRole('textbox', { name: 'Link' }).inputValue();
  await page.getByRole('link').getByRole('button').click();
  await expect(page.getByRole('cell', { name: fileName })).toBeVisible();
  const downloadPromise = page.waitForEvent('download');
  

  await page.locator('.mantine-UnstyledButton-root.mantine-ActionIcon-root.mantine-1lkzm3m').click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe(fileName);
});